project:
  type: website
  output-dir: docs

language: 
  search-text-placeholder: Search
  
website:
  title: "Olivier Binette"
  site-url: "https://olivierbinette.ca"
  twitter-card: true
  open-graph: true
  google-analytics:
      tracking-id: "G-059GDHV0GP"
      anonymize-ip: false
  search:
    location: navbar
    type: overlay
  navbar:
    right:
      - href: index.qmd
        text: "Home"
      - href: pages/blog.qmd
        text: "Blog"
      - href: pages/research.qmd
        text: "Publications"
      - href: pages/software.qmd
        text: "Software"
      - href: pages/teaching.qmd
        text: "Teaching"
      - icon: github
        href: https://www.github.com/OlivierBinette
      - icon: rss
        href: pages/blog.xml
  page-footer:
    center: 
      - text: "Copyright &#169 2024 Olivier Binette"
    background: "#fafafa"

format:
  html:
    author-meta: Olivier Binette
    theme:
      - cosmo
      - theming.scss
    toc: true
    toc-location: left
    code-fold: show
    code-line-numbers: true
    code-copy: true
    code-annotations: hover
    highlight-style: github
    email-obfuscation: references
    title-block-banner: "#f8f8f8"
    title-block-banner-color: "#c00000"

