---
title: "Consulting"
output:
  distill::distill_article:
    toc: false
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

I consult with small and medium-sized businesses on the topics of record linkage and deduplication, survey methods, data analysis, R/Python package development, and statistical learning. 

Specifically, I can help you and your team:

- Validate your approaches and statistical methodology.
- Improve your data science software development practices and ensure the reproducibility of your data analyses.
- Quantify uncertainty surrounding your predictions and inferences using conformal prediction, resampling, and Bayesian methods.
- Evaluate the effectiveness of your programs and activites through data and experiments.
- Integrate data from multiple sources using record linkage and entity resolution algorithms.
- Train your staff to effectively work with R, Python, git, and bash as part of a data science workflow.

Use the form below to contact me and learn more about my services:

<form id="fs-frm" name="simple-contact-form" accept-charset="utf-8" action="https://formspree.io/f/meqnoddy" method="post">
  <fieldset id="fs-frm-inputs">
    <label for="full-name"></label>
    <input type="text" name="name" id="full-name" placeholder="Name" required="">
    <label for="email-address"></label>
    <input type="email" name="_replyto" id="email-address" placeholder="Email" required="">
    <label for="message"></label>
    <textarea rows="5" name="message" id="message" placeholder="Message" required=""></textarea>
    <input type="hidden" name="_subject" id="email-subject" value="Contact Form Submission">
  </fieldset>
  
  <input id="form_button" type="submit" value="Submit">
</form>


## What to expect

I will get back to you to schedule a short introduction meeting. My goal is to understand the problem you're facing and the outcome that you are looking for. If we determine that I'm a good fit, I will then send you a work plan, a pricing estimate, and a draft consulting agreement for your approval.

My priority is to *make happen* your desired outcome. I will work with you to define a project scope which is compatible with your budget and which brings significant value to your organization.


