---
title: "Research"
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Evaluation

- Binette, O., S. A. York, E. Hickerson, Y. Baek, S. Madhavan and C. Jones. (2022) Practical Performance Evaluation of Entity Resolution Algorithms: Lessons Learned at PatentsView.org. [[pdf](media/PatentsView-Evaluation.pdf)]

### Multiple systems estimation

- Binette, O. and Steorts, R. C. (2021) On the Reliability of Multiple Systems Estimation for the Quantification of Modern Slavery. *Journal of the Royal Statistical Society, Series A*  [[link]](https://rss.onlinelibrary.wiley.com/doi/10.1111/rssa.12803) [[pdf]](https://arxiv.org/abs/2112.01594)
- Binette, O. and Steorts, R. C. (2020) Discussion of read paper "Multiple-systems analysis for the quantification of modern slavery: classical and Bayesian approaches" by Bernard Silverman. *Journal of the Royal Statistical Society Series A 183* (3). pp. 35 [[link](https://rss.onlinelibrary.wiley.com/doi/10.1111/rssa.12505)]

### Entity resolution

- Binette, O. and Steorts, R. C. (2021) Modern Bayesian Entity Resolution. *Wiley StatsRef* [[link]](https://doi.org/10.1002/9781118445112.stat08367)
- Binette, O. and Steorts, R. C. (2021) (Almost) All of Entity Resolution. *Science Advances 8* (12) [[link]](https://www.science.org/doi/full/10.1126/sciadv.abi8021)


### Bayesian nonparametrics


- Binette, O. and Pati, D. and Dunson, D. B. (2020) Bayesian Closed Surface Fitting Through Tensor Products. *Journal of Machine Learning Research 21* (119) pp. 1-26 [[pdf](https://jmlr.org/papers/volume21/13-233/13-233.pdf)]

- Binette, O. (2019). A Note on Reverse Pinsker Inequalities. *IEEE Transactions on Information Theory 65* (7). pp.4094-4096. [[pdf]](https://arxiv.org/pdf/1805.05135.pdf)

- Binette, O. and Guillotte, S. (2019). Bayesian Nonparametrics for Directional Statistics. *arXiv e-prints.* arxiv:1807.00305. [[pdf](https://arxiv.org/pdf/1807.00305.pdf)]

<!--### Side projects (posters)

- Binette, O. (2018). Topology and Machine Learning. *Notes from the Margin 13*. pp. 5-6.	[[link](https://issuu.com/cms-studc/docs/margin-spring2018)]

- Binette, O. and Luo, L. An Analysis of Gibbs Posterior Concentration in Terms of the Separation $\alpha$-Entropy. *Objective Bayes Conference* (poster presentation). Warwick (United Kingdom). June 28, 2019. [[pdf](media/poster.pdf)]

- Binette, O. and Coache, A. The Significance of the Adjusted R Squared. *(Bio)Statistics Research Day* (poster presentation). Montréal (Canada). September 21, 2018. [[pdf](media/poster adjusted R2.pdf)]

- Binette, O. Classification and Topology, or Consequences of Sobolev Consistency. *Canadian Statistics Student Conference* (poster presentation). Montréal (Canada). June 2, 2018. (Best poster award) [[pdf](media/poster topology and machine learning.pdf)]

-->
