---
title: "Values"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

I am committed to making the world a better place through my work. The most fundamental values which underpin my commitment are listed below.

-   I have always thought of mathematics and statistics as **liberal arts**. They are tools to help us make better sense of the world. I want to pursue research in a way which is compatible with this point of view and which ultimately promotes **free and critical thought**.

-   I want my research, teaching, and mentoring to be positive not just in terms of their direct intended purposes, but also through their **collateral effects**. This includes their effects on **well-being, on intellectual training, and on personal growth** for trainees, students, collaborators, and for the broader community.

-   I want my research to be **open and freely accessible**. Feedback and criticism is always welcome.

-   I want to **acknowledge uncertainty and uphold truth** in my work, despite potential pressure to the contrary. Too often we see wild claims from weak observational studies in the scientific literature. Science cannot be reduced to "$p < 0.05$".

-   **Compromises are necessary** to rally people. I do not compromise on core principles of truth and inclusivity, but I otherwise want to be accommodating with collegiality in mind.
