---
title: "Loomis-Whitney type inequality for quasi-balls?"
author:
  - name: Olivier Binette
date: 02-10-2017
output:
  distill::distill_article:
    self_contained: false
---

Consider the problem of estimating the volume of a tumor, given X-ray scans along orthogonal axes. It may be known that the tumor has a somewhat spherical shape. To formalise this idea, let $T \subset \mathbb{R}^3$ be the tumor, $s$ the area of its surface, $m$ its volume and $C = s^3/m^2$. From the isoperimetric inequality, we have $C \geq 6^2 \pi$, with equality iff $T$ is a ball. Correspondingly, we say that $T$ is a quasi-ball if $C \approx 6^2 \pi$. In reality, $C$ is unknown but its distribution may be determined.

We are now given the areas $m_1$, $m_2$ and $m_3$ of the projections of $T$ along orthogonal axes. From the Loomis-Whitney inequality (or Cauchy-Schwarz in this case), we have the following estimate of the volume $m$ of $T$.

**Theorem.**
<em>We have</em>

$$\max_i \sqrt{\frac{2^3 m_i^3}{C}} \le m \le \sqrt{m_1 m_2 m_3}.$$

**Problem.**
<em>Can we find such an estimate of $m$ that is close to sharp when $T$ is close to a ball?</em>

**References.**
<span id="dynamic_citation">Loomis, L. H.; Whitney, H. An inequality related to the isoperimetric inequality. Bull. Amer. Math. Soc. 55 (1949), no. 10, 961--962.</span> http://projecteuclid.org/euclid.bams/1183514163.
