---
title: "What is the Reality-Ideality-Gap in Entity Resolution?"
date: 2023-12-12
categories:
  - technical
  - record-linkage
---

[Wang et al (2022)](https://www.ijcai.org/proceedings/2022/0552.pdf) describe the frustration when real-world performance does not match expectations obtained from benchmark datasets. This difference is the "reality-ideality" gap which is all too common in real-world applications of entity resolution.\
\
Why does it happen? They posit that three main issues limit the generalizability of current benchmarks, specifically in the context of deep learning approaches to entity resolution:\
\
1. ð“ð¡ðžð«ðž ð¢ð¬ ð¥ðžðšð¤ðšð ðž ðŸð«ð¨ð¦ ð­ð¡ðž ð­ð«ðšð¢ð§ð¢ð§ð  ð¬ðžð­ ð¢ð§ð­ð¨ ð­ð¡ðž ð­ðžð¬ð­ ð¬ðžð­. In typical benchmark constructions, record pairs are randomly sampled, leading to the same cluster being represented in both the train and test dataset. This biases results, especially in deep learning approaches which rely on learning record embeddings.\
\
2. ð‘ðžðšð¥-ð°ð¨ð«ð¥ð ððšð­ðš ð¢ð¬ ð¦ð®ðœð¡ ð¦ð¨ð«ðž ð¢ð¦ð›ðšð¥ðšð§ðœðžð ð­ð¡ðšð§ ð›ðžð§ðœð¡ð¦ðšð«ð¤ ððšð­ðšð¬ðžð­ð¬ in terms of matching vs non-matching record pairs. In other words, there is much more opportunity for error in real data than in a benchmark dataset.\
\
3. Partly as a consequence of the two above issues, ð­ð²ð©ð¢ðœðšð¥ ð›ðžð§ðœð¡ð¦ðšð«ð¤ð¬ ð®ð§ððžð«ðžð¬ð­ð¢ð¦ðšð­ðž ð­ð¡ðž ð¢ð¦ð©ð¨ð«ð­ðšð§ðœðž ð¨ðŸ ðšððð¢ð­ð¢ð¨ð§ðšð¥ ðŸðžðšð­ð®ð«ðžð¬ ðšð§ð ð¦ð®ð¥ð­ð¢ð¦ð¨ððšð¥ ð¢ð§ðŸð¨ð«ð¦ðšð­ð¢ð¨ð§. This leads to under-specified systems which do not perform as well as they could.\
\
The paper goes on to define clear tasks for entity resolution systems and detail issues with current benchmarks:\

> "Our findings reveal that previous benchmarks biased the evaluation of the progress of current entity matching approaches, and there is still a long way to go to build effective entity matchers."

<embed src="https://www.ijcai.org/proceedings/2022/0552.pdf" width="100%" height="100%"/>
