---
title: "Open-Source Software"
---

## Python Packages

| Project | Description | Role |
|----|-------------|---|
|[PatentsView-Code-Examples](https://github.com/PatentsView/PatentsView-Code-Examples)| Training resources for working with PatentsView APIs and Open Data. | Lead |
| [Deepchecks' PerformanceBias](https://kagi.com/search?q=deepchecks+performance+bias) |  Contributed the `performance_bias` module to Deepchecks' open-source package (3.7k+ stars on Github). |  Core Contributor |
| [Streamlit-Survey](https://github.com/Valires/streamlit-survey)  | Survey components for Streamlit apps. | Creator |
| [CSVMeta](https://github.com/OlivierBinette/CSVMeta)  | Lightweight csv read/write, keeping track of csv dialect and other metadata.  | Creator |
| [ER-Evaluation](https://github.com/Valires/er-evaluation)  | End-to-end evaluation of entity resolution systems.  | Creator |
| [StringCompare](https://github.com/olivierbinette/StringCompare) | Efficient string similarity using C++ and PyBind11. | Creator  |


## R Packages

| Project | Description | Role |
|----|-------------|---|
| [MSETools](https://github.com/OlivierBinette/MSETools) | Code and analyses for the paper titled “On the Reliability of Multiple Systems Estimation for the Quantification of Modern Slavery” (Binette and Steorts, 2021). | Creator |
| [FingermatchR](https://github.com/forensic-science/fingermatchR) | Fingerprint matching tools based on NIST's Biometric Image Software, on FingerJet minutiae extraction tool, and on the libfmr library. | Creator |
| [cache](https://github.com/OlivierBinette/cache) | Lightweight caching for data science workflows.| Creator |
| [assert](https://github.com/OlivierBinette/assert) | Lightweight assertions for data science workflows. | Creator |
| [dgaFast/dga](https://github.com/olivierBinette/dgaFast) | Multiple Systems Estimation Using Decomposable Graphical Models. | Maintainer |
| [TessTools](https://github.com/OlivierBinette/TessTools) | Tools for the use of Tesseract OCR in R and for the analysis of historical newspaper archives. | Creator |


## Other Software

| Project | Description | Role |
|----|-------------|---|
| [Fractals](https://olivierbinette.github.io/Fractals/) | A Javascript Mendelbrot set visualization app, built using early browser multithreading technologies (2014). | Creator |
| [Welcome to the Moon App](https://github.com/OlivierBinette/welcome-to-the-moon-card-flipper) | Companion app to the wonderful *Welcome to the Moon* board game. | Creator |
| [Earthquakes](https://olivierbinette.github.io/earthquakes/) | Visualize earthquakes on the globe. | Creator |
| [lipsample](https://github.com/OlivierBinette/lipsample) | Sampling from arbitrary Lipschitz continuous densities on the interval in Matlab | Creator |
